name: Swift Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Swift
    runs-on: macos-latest
    steps:
      - name: Select specific XCode
        run: sudo xcode-select -s /Applications/Xcode_15.3.app

      - uses: actions/checkout@v4

      - name: Build
        run: xcodebuild build -scheme SdkMobileIOSNative -sdk "`xcrun --sdk iphonesimulator --show-sdk-path`" -destination "OS=17.4,name=iPhone 15"

      - name: Run tests
        run: xcodebuild test -scheme SdkMobileIOSNative -sdk "`xcrun --sdk iphonesimulator --show-sdk-path`" -destination "platform=iOS Simulator,OS=17.4,name=iPhone 15"
