name: Lint and Format code

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  lint:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v6

      - name: Wait for simulators
        run: xcrun simctl list

      - run: brew install swiftlint

      - run: brew install peripheryapp/periphery/periphery

      - run: swiftlint lint .

      - run: swiftformat --lint .

      - run: .github/workflows/unused-variables.sh

  pr-check:
    name: PR Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: read
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/pr-check
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

